# Generated by Django 5.1.15 on 2026-02-13 21:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import victims.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(max_length=120)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Victim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("native_name", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("city_of_death", models.CharField(max_length=120)),
                ("province_or_state", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
                ("biography", models.TextField(blank=True)),
                ("short_summary", models.TextField(blank=True)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("education", models.CharField(blank=True, max_length=200)),
                ("marital_status", models.CharField(blank=True, max_length=100)),
                (
                    "children_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("family_contact_private", models.TextField(blank=True)),
                ("burial_location", models.CharField(blank=True, max_length=200)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitter_name", models.CharField(blank=True, max_length=120)),
                ("submitter_email", models.EmailField(blank=True, max_length=254)),
                ("proposed_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "victim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="victims.victim",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("publisher_name", models.CharField(max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "credibility_score",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="victims.victim",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="victims/photos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            victims.models.validate_image_size,
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("photographer_credit", models.CharField(blank=True, max_length=255)),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="victims.victim",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="VictimTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="victims.tag"
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="victims.victim"
                    ),
                ),
            ],
            options={
                "unique_together": {("victim", "tag")},
            },
        ),
        migrations.AddField(
            model_name="victim",
            name="tags",
            field=models.ManyToManyField(
                related_name="victims", through="victims.VictimTag", to="victims.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="victim",
            index=models.Index(
                fields=["full_name"], name="victims_vic_full_na_2c0359_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victim",
            index=models.Index(
                fields=["city_of_death"], name="victims_vic_city_of_a55f63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victim",
            index=models.Index(
                fields=["date_of_death"], name="victims_vic_date_of_028b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victim",
            index=models.Index(
                fields=["verification_status"], name="victims_vic_verific_5bb76c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victim",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="victim_search_vector_gin"
            ),
        ),
    ]
